<?php


class LibJulian extends \ProcessWire\WireData implements \ProcessWire\Module {

  public static function getModuleInfo() {
    return array(
      'title' => 'Julian Calendar Framework',
      'version' => 90,
      'summary' => 'Adds auto-loading functionality of Julian classes to your PW install',
      'singular' => true,
      'autoload' => true
      );
  }

  public function init() {
    spl_autoload_register(array($this, 'julianLoader'));
  }

  private function julianLoader(){
 include_once(\ProcessWire\wire('files')->compile("julian/Julian.php",array('includes'=>true,'namespace'=>true,'modules'=>false,'skipIfNamespace'=>false)));
 include_once(\ProcessWire\wire('files')->compile("julian/Julian_Day.php",array('includes'=>true,'namespace'=>true,'modules'=>false,'skipIfNamespace'=>false)));
 include_once(\ProcessWire\wire('files')->compile("julian/Julian_Week.php",array('includes'=>true,'namespace'=>true,'modules'=>false,'skipIfNamespace'=>false)));
 include_once(\ProcessWire\wire('files')->compile("julian/Julian_Event.php",array('includes'=>true,'namespace'=>true,'modules'=>false,'skipIfNamespace'=>false)));
  }
}